[opener]
text = [
  { run = 'hx "$@"', block = true },
]
preview = [
  { run = 'open "$@"'}
]
helix = [
  { run = 'hx "$@"', block = true, desc = "Use yazi as file picker within helix" },
]

[mgr]
sort_dir_first = true
ratio = [2, 2, 5]
sort_by = "natural"
show_hidden = true

# you probably want other mime types to be opened differently
[open]
rules = [
  { name = "**/*", use = "helix" },
]
